<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20200924191117 extends AbstractMigration
{
    public function getDescription() : string
    {
        return '';
    }

    public function up(Schema $schema) : void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE twitter_likes DROP FOREIGN KEY FK_twitter_likes_twitter_accounts');
        $this->addSql('ALTER TABLE twitter_tweets DROP FOREIGN KEY FK_twitter_tweets_twitter_accounts');
        $this->addSql('ALTER TABLE twitter_likes DROP FOREIGN KEY FK_twitter_likes_twitter_tweets');
        $this->addSql('DROP TABLE addon_account');
        $this->addSql('DROP TABLE addon_account_data');
        $this->addSql('DROP TABLE addon_inventory');
        $this->addSql('DROP TABLE addon_inventory_items');
        $this->addSql('DROP TABLE aircraft_categories');
        $this->addSql('DROP TABLE aircraftdealer_aircrafts');
        $this->addSql('DROP TABLE aircrafts');
        $this->addSql('DROP TABLE billing');
        $this->addSql('DROP TABLE boat_categories');
        $this->addSql('DROP TABLE boatdealer_boats');
        $this->addSql('DROP TABLE boats');
        $this->addSql('DROP TABLE car_parking');
        $this->addSql('DROP TABLE cardealer_vehicles');
        $this->addSql('DROP TABLE characters');
        $this->addSql('DROP TABLE datastore');
        $this->addSql('DROP TABLE datastore_data');
        $this->addSql('DROP TABLE fine_types');
        $this->addSql('DROP TABLE fine_types_biker');
        $this->addSql('DROP TABLE fine_types_gang');
        $this->addSql('DROP TABLE fine_types_gouv');
        $this->addSql('DROP TABLE fine_types_mafia');
        $this->addSql('DROP TABLE items');
        $this->addSql('DROP TABLE jail');
        $this->addSql('DROP TABLE job_grades');
        $this->addSql('DROP TABLE jobs');
        $this->addSql('DROP TABLE licenses');
        $this->addSql('DROP TABLE org');
        $this->addSql('DROP TABLE org_gradeorg');
        $this->addSql('DROP TABLE organisation_moneywash');
        $this->addSql('DROP TABLE owned_aircrafts');
        $this->addSql('DROP TABLE owned_boats');
        $this->addSql('DROP TABLE owned_properties');
        $this->addSql('DROP TABLE owned_vehicles');
        $this->addSql('DROP TABLE phone_app_chat');
        $this->addSql('DROP TABLE phone_calls');
        $this->addSql('DROP TABLE phone_messages');
        $this->addSql('DROP TABLE phone_users_contacts');
        $this->addSql('DROP TABLE playerstattoos');
        $this->addSql('DROP TABLE properties');
        $this->addSql('DROP TABLE rented_aircrafts');
        $this->addSql('DROP TABLE rented_boats');
        $this->addSql('DROP TABLE rented_vehicles');
        $this->addSql('DROP TABLE shops');
        $this->addSql('DROP TABLE shops2');
        $this->addSql('DROP TABLE society_moneywash');
        $this->addSql('DROP TABLE truck_inventory');
        $this->addSql('DROP TABLE twitter_accounts');
        $this->addSql('DROP TABLE twitter_likes');
        $this->addSql('DROP TABLE twitter_tweets');
        $this->addSql('DROP TABLE user_accessories');
        $this->addSql('DROP TABLE user_accounts');
        $this->addSql('DROP TABLE user_contacts');
        $this->addSql('DROP TABLE user_inventory');
        $this->addSql('DROP TABLE user_licenses');
        $this->addSql('DROP TABLE user_parkings');
        $this->addSql('DROP TABLE user_tenue');
        $this->addSql('DROP TABLE vehicle_categories');
        $this->addSql('DROP TABLE vehicle_sold');
        $this->addSql('DROP TABLE vehicles');
        $this->addSql('DROP TABLE weashops');
        $this->addSql('DROP TABLE whitelist');
        $this->addSql('DROP INDEX identifier ON users');
        $this->addSql('DROP INDEX name ON users');
        $this->addSql('ALTER TABLE users ADD id INT AUTO_INCREMENT NOT NULL, ADD user_id_id INT DEFAULT NULL, CHANGE name name VARCHAR(50) DEFAULT NULL, CHANGE job job VARCHAR(50) DEFAULT NULL, CHANGE job_grade job_grade INT DEFAULT NULL, CHANGE job2 job2 VARCHAR(255) DEFAULT NULL, CHANGE job2_grade job2_grade INT DEFAULT NULL, CHANGE is_dead is_dead SMALLINT DEFAULT NULL, CHANGE firstname firstname VARCHAR(255) DEFAULT NULL, CHANGE lastname lastname VARCHAR(255) DEFAULT NULL, CHANGE dateofbirth dateofbirth VARCHAR(255) DEFAULT NULL, CHANGE sex sex VARCHAR(255) DEFAULT NULL, CHANGE height height VARCHAR(255) DEFAULT NULL, CHANGE status status LONGTEXT NOT NULL, CHANGE jail jail INT DEFAULT NULL, CHANGE phone_number phone_number VARCHAR(255) DEFAULT NULL, ADD PRIMARY KEY (id)');
        $this->addSql('ALTER TABLE users ADD CONSTRAINT FK_1483A5E99D86650F FOREIGN KEY (user_id_id) REFERENCES user (id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_1483A5E99D86650F ON users (user_id_id)');
    }

    public function down(Schema $schema) : void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE addon_account (name VARCHAR(60) CHARACTER SET latin1 NOT NULL COLLATE `latin1_swedish_ci`, label VARCHAR(100) CHARACTER SET latin1 NOT NULL COLLATE `latin1_swedish_ci`, shared INT NOT NULL, PRIMARY KEY(name)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE addon_account_data (id INT AUTO_INCREMENT NOT NULL, account_name VARCHAR(100) CHARACTER SET latin1 DEFAULT NULL COLLATE `latin1_swedish_ci`, money INT NOT NULL, owner VARCHAR(255) CHARACTER SET latin1 DEFAULT NULL COLLATE `latin1_swedish_ci`, UNIQUE INDEX index_addon_account_data_account_name_owner (account_name, owner), INDEX index_addon_account_data_account_name (account_name), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE addon_inventory (name VARCHAR(60) CHARACTER SET latin1 NOT NULL COLLATE `latin1_swedish_ci`, label VARCHAR(255) CHARACTER SET latin1 NOT NULL COLLATE `latin1_swedish_ci`, shared INT NOT NULL, PRIMARY KEY(name)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE addon_inventory_items (id INT AUTO_INCREMENT NOT NULL, inventory_name VARCHAR(100) CHARACTER SET latin1 NOT NULL COLLATE `latin1_swedish_ci`, name VARCHAR(100) CHARACTER SET latin1 NOT NULL COLLATE `latin1_swedish_ci`, count INT NOT NULL, owner VARCHAR(60) CHARACTER SET latin1 DEFAULT NULL COLLATE `latin1_swedish_ci`, INDEX index_addon_inventory_inventory_name (inventory_name), INDEX index_addon_inventory_items_inventory_name_name (inventory_name, name), INDEX index_addon_inventory_items_inventory_name_name_owner (inventory_name, name, owner), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE aircraft_categories (name VARCHAR(60) CHARACTER SET latin1 NOT NULL COLLATE `latin1_swedish_ci`, label VARCHAR(60) CHARACTER SET latin1 NOT NULL COLLATE `latin1_swedish_ci`, PRIMARY KEY(name)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = MyISAM COMMENT = \'\' ');
        $this->addSql('CREATE TABLE aircraftdealer_aircrafts (id INT AUTO_INCREMENT NOT NULL, vehicle VARCHAR(255) CHARACTER SET latin1 NOT NULL COLLATE `latin1_swedish_ci`, price INT NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = MyISAM COMMENT = \'\' ');
        $this->addSql('CREATE TABLE aircrafts (model VARCHAR(60) CHARACTER SET latin1 NOT NULL COLLATE `latin1_swedish_ci`, name VARCHAR(60) CHARACTER SET latin1 NOT NULL COLLATE `latin1_swedish_ci`, price INT NOT NULL, category VARCHAR(60) CHARACTER SET latin1 DEFAULT NULL COLLATE `latin1_swedish_ci`, PRIMARY KEY(model)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = MyISAM COMMENT = \'\' ');
        $this->addSql('CREATE TABLE billing (id INT AUTO_INCREMENT NOT NULL, identifier VARCHAR(255) CHARACTER SET latin1 NOT NULL COLLATE `latin1_swedish_ci`, sender VARCHAR(255) CHARACTER SET latin1 NOT NULL COLLATE `latin1_swedish_ci`, target_type VARCHAR(50) CHARACTER SET latin1 NOT NULL COLLATE `latin1_swedish_ci`, target VARCHAR(255) CHARACTER SET latin1 NOT NULL COLLATE `latin1_swedish_ci`, label VARCHAR(255) CHARACTER SET latin1 NOT NULL COLLATE `latin1_swedish_ci`, amount INT NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE boat_categories (name VARCHAR(60) CHARACTER SET latin1 NOT NULL COLLATE `latin1_swedish_ci`, label VARCHAR(60) CHARACTER SET latin1 NOT NULL COLLATE `latin1_swedish_ci`, PRIMARY KEY(name)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = MyISAM COMMENT = \'\' ');
        $this->addSql('CREATE TABLE boatdealer_boats (id INT AUTO_INCREMENT NOT NULL, vehicle VARCHAR(255) CHARACTER SET latin1 NOT NULL COLLATE `latin1_swedish_ci`, price INT NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = MyISAM COMMENT = \'\' ');
        $this->addSql('CREATE TABLE boats (model VARCHAR(60) CHARACTER SET latin1 NOT NULL COLLATE `latin1_swedish_ci`, name VARCHAR(60) CHARACTER SET latin1 NOT NULL COLLATE `latin1_swedish_ci`, price INT NOT NULL, category VARCHAR(60) CHARACTER SET latin1 DEFAULT NULL COLLATE `latin1_swedish_ci`, PRIMARY KEY(model)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = MyISAM COMMENT = \'\' ');
        $this->addSql('CREATE TABLE car_parking (id INT AUTO_INCREMENT NOT NULL, owner VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, plate VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, data LONGTEXT CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, time BIGINT NOT NULL, parking VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE cardealer_vehicles (id INT AUTO_INCREMENT NOT NULL, vehicle VARCHAR(255) CHARACTER SET latin1 NOT NULL COLLATE `latin1_swedish_ci`, price INT NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE characters (id INT AUTO_INCREMENT NOT NULL, identifier VARCHAR(255) CHARACTER SET latin1 NOT NULL COLLATE `latin1_swedish_ci`, firstname VARCHAR(255) CHARACTER SET latin1 NOT NULL COLLATE `latin1_swedish_ci`, lastname VARCHAR(255) CHARACTER SET latin1 NOT NULL COLLATE `latin1_swedish_ci`, dateofbirth VARCHAR(255) CHARACTER SET latin1 NOT NULL COLLATE `latin1_swedish_ci`, sex VARCHAR(1) CHARACTER SET latin1 DEFAULT \'M\' NOT NULL COLLATE `latin1_swedish_ci`, height VARCHAR(128) CHARACTER SET latin1 NOT NULL COLLATE `latin1_swedish_ci`, INDEX identifier (identifier), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE datastore (name VARCHAR(60) CHARACTER SET latin1 NOT NULL COLLATE `latin1_swedish_ci`, label VARCHAR(255) CHARACTER SET latin1 NOT NULL COLLATE `latin1_swedish_ci`, shared INT NOT NULL, PRIMARY KEY(name)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE datastore_data (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(60) CHARACTER SET latin1 NOT NULL COLLATE `latin1_swedish_ci`, owner VARCHAR(60) CHARACTER SET latin1 DEFAULT NULL COLLATE `latin1_swedish_ci`, data LONGTEXT CHARACTER SET latin1 DEFAULT NULL COLLATE `latin1_swedish_ci`, UNIQUE INDEX index_datastore_data_name_owner (name, owner), INDEX index_datastore_data_name (name), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE fine_types (id INT AUTO_INCREMENT NOT NULL, label VARCHAR(255) CHARACTER SET latin1 DEFAULT NULL COLLATE `latin1_swedish_ci`, amount INT DEFAULT NULL, category INT DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE fine_types_biker (id INT AUTO_INCREMENT NOT NULL, label VARCHAR(255) CHARACTER SET latin1 DEFAULT NULL COLLATE `latin1_swedish_ci`, amount INT DEFAULT NULL, category INT DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE fine_types_gang (id INT AUTO_INCREMENT NOT NULL, label VARCHAR(255) CHARACTER SET latin1 DEFAULT NULL COLLATE `latin1_swedish_ci`, amount INT DEFAULT NULL, category INT DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE fine_types_gouv (id INT AUTO_INCREMENT NOT NULL, label VARCHAR(255) CHARACTER SET latin1 DEFAULT NULL COLLATE `latin1_swedish_ci`, amount INT DEFAULT NULL, category INT DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE fine_types_mafia (id INT AUTO_INCREMENT NOT NULL, label VARCHAR(255) CHARACTER SET latin1 DEFAULT NULL COLLATE `latin1_swedish_ci`, amount INT DEFAULT NULL, category INT DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE items (name VARCHAR(50) CHARACTER SET latin1 NOT NULL COLLATE `latin1_swedish_ci`, label VARCHAR(50) CHARACTER SET latin1 NOT NULL COLLATE `latin1_swedish_ci`, `limit` INT DEFAULT -1 NOT NULL, rare INT DEFAULT 0 NOT NULL, can_remove INT DEFAULT 1 NOT NULL, PRIMARY KEY(name)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE jail (identifier VARCHAR(100) CHARACTER SET latin1 NOT NULL COLLATE `latin1_swedish_ci`, isjailed TINYINT(1) DEFAULT NULL, J_Time DATETIME NOT NULL, J_Cell VARCHAR(20) CHARACTER SET latin1 NOT NULL COLLATE `latin1_swedish_ci`, Jailer VARCHAR(100) CHARACTER SET latin1 NOT NULL COLLATE `latin1_swedish_ci`, Jailer_ID VARCHAR(100) CHARACTER SET latin1 NOT NULL COLLATE `latin1_swedish_ci`, PRIMARY KEY(identifier)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE job_grades (id INT AUTO_INCREMENT NOT NULL, job_name VARCHAR(50) CHARACTER SET latin1 DEFAULT NULL COLLATE `latin1_swedish_ci`, grade INT NOT NULL, name VARCHAR(50) CHARACTER SET latin1 NOT NULL COLLATE `latin1_swedish_ci`, label VARCHAR(50) CHARACTER SET latin1 NOT NULL COLLATE `latin1_swedish_ci`, salary INT NOT NULL, skin_male LONGTEXT CHARACTER SET latin1 NOT NULL COLLATE `latin1_swedish_ci`, skin_female LONGTEXT CHARACTER SET latin1 NOT NULL COLLATE `latin1_swedish_ci`, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE jobs (name VARCHAR(50) CHARACTER SET latin1 NOT NULL COLLATE `latin1_swedish_ci`, label VARCHAR(50) CHARACTER SET latin1 DEFAULT NULL COLLATE `latin1_swedish_ci`, whitelisted TINYINT(1) DEFAULT \'0\' NOT NULL, SecondaryJob TINYINT(1) DEFAULT \'0\' NOT NULL, PRIMARY KEY(name)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE licenses (type VARCHAR(60) CHARACTER SET latin1 NOT NULL COLLATE `latin1_swedish_ci`, label VARCHAR(60) CHARACTER SET latin1 NOT NULL COLLATE `latin1_swedish_ci`, PRIMARY KEY(type)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE org (name VARCHAR(50) CHARACTER SET latin1 NOT NULL COLLATE `latin1_swedish_ci`, label VARCHAR(255) CHARACTER SET latin1 DEFAULT NULL COLLATE `latin1_swedish_ci`, PRIMARY KEY(name)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE org_gradeorg (id INT AUTO_INCREMENT NOT NULL, org_name VARCHAR(255) CHARACTER SET latin1 DEFAULT NULL COLLATE `latin1_swedish_ci`, gradeorg INT NOT NULL, name VARCHAR(255) CHARACTER SET latin1 NOT NULL COLLATE `latin1_swedish_ci`, label VARCHAR(255) CHARACTER SET latin1 NOT NULL COLLATE `latin1_swedish_ci`, salary INT NOT NULL, skin_male LONGTEXT CHARACTER SET latin1 NOT NULL COLLATE `latin1_swedish_ci`, skin_female LONGTEXT CHARACTER SET latin1 NOT NULL COLLATE `latin1_swedish_ci`, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE organisation_moneywash (id INT AUTO_INCREMENT NOT NULL, identifier VARCHAR(60) CHARACTER SET latin1 NOT NULL COLLATE `latin1_swedish_ci`, organisation VARCHAR(60) CHARACTER SET latin1 NOT NULL COLLATE `latin1_swedish_ci`, amount INT NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE owned_aircrafts (plate VARCHAR(12) CHARACTER SET latin1 NOT NULL COLLATE `latin1_swedish_ci`, owner VARCHAR(30) CHARACTER SET latin1 NOT NULL COLLATE `latin1_swedish_ci`, state TINYINT(1) DEFAULT \'0\' NOT NULL COMMENT \'State of the aircraft\', vehicle LONGTEXT CHARACTER SET latin1 DEFAULT NULL COLLATE `latin1_swedish_ci`, PRIMARY KEY(plate)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = MyISAM COMMENT = \'\' ');
        $this->addSql('CREATE TABLE owned_boats (plate VARCHAR(12) CHARACTER SET latin1 NOT NULL COLLATE `latin1_swedish_ci`, owner VARCHAR(30) CHARACTER SET latin1 NOT NULL COLLATE `latin1_swedish_ci`, state TINYINT(1) DEFAULT \'0\' NOT NULL COMMENT \'State of the boat\', vehicle LONGTEXT CHARACTER SET latin1 DEFAULT NULL COLLATE `latin1_swedish_ci`, PRIMARY KEY(plate)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = MyISAM COMMENT = \'\' ');
        $this->addSql('CREATE TABLE owned_properties (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) CHARACTER SET latin1 NOT NULL COLLATE `latin1_swedish_ci`, price DOUBLE PRECISION NOT NULL, rented INT NOT NULL, owner VARCHAR(60) CHARACTER SET latin1 NOT NULL COLLATE `latin1_swedish_ci`, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE owned_vehicles (plate VARCHAR(12) CHARACTER SET latin1 NOT NULL COLLATE `latin1_swedish_ci`, owner VARCHAR(22) CHARACTER SET latin1 NOT NULL COLLATE `latin1_swedish_ci`, state TINYINT(1) DEFAULT \'0\' NOT NULL COMMENT \'Etat de la voiture\', vehicle LONGTEXT CHARACTER SET latin1 DEFAULT NULL COLLATE `latin1_swedish_ci`, type VARCHAR(20) CHARACTER SET latin1 DEFAULT \'car\' NOT NULL COLLATE `latin1_swedish_ci`, job VARCHAR(20) CHARACTER SET latin1 DEFAULT NULL COLLATE `latin1_swedish_ci`, `stored` TINYINT(1) DEFAULT \'0\' NOT NULL, garage VARCHAR(200) CHARACTER SET latin1 DEFAULT \'A\' COLLATE `latin1_swedish_ci`, PRIMARY KEY(plate)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE phone_app_chat (id INT AUTO_INCREMENT NOT NULL, channel VARCHAR(20) CHARACTER SET utf8 NOT NULL COLLATE `utf8_general_ci`, message VARCHAR(255) CHARACTER SET utf8 NOT NULL COLLATE `utf8_general_ci`, time DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE phone_calls (id INT AUTO_INCREMENT NOT NULL, owner VARCHAR(10) CHARACTER SET utf8 NOT NULL COLLATE `utf8_general_ci` COMMENT \'Num tel proprio\', num VARCHAR(10) CHARACTER SET utf8 NOT NULL COLLATE `utf8_general_ci` COMMENT \'Num reférence du contact\', incoming INT NOT NULL COMMENT \'Défini si on est à l\'\'origine de l\'\'appels\', time DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL, accepts INT NOT NULL COMMENT \'Appels accepter ou pas\', PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE phone_messages (id INT AUTO_INCREMENT NOT NULL, transmitter VARCHAR(10) CHARACTER SET utf8 NOT NULL COLLATE `utf8_general_ci`, receiver VARCHAR(10) CHARACTER SET utf8 NOT NULL COLLATE `utf8_general_ci`, message VARCHAR(255) CHARACTER SET utf8 DEFAULT \'0\' NOT NULL COLLATE `utf8_general_ci`, time DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL, isRead INT DEFAULT 0 NOT NULL, owner INT DEFAULT 0 NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = MyISAM COMMENT = \'\' ');
        $this->addSql('CREATE TABLE phone_users_contacts (id INT AUTO_INCREMENT NOT NULL, identifier VARCHAR(60) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_general_ci`, number VARCHAR(10) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_general_ci`, display VARCHAR(64) CHARACTER SET utf8mb4 DEFAULT \'-1\' NOT NULL COLLATE `utf8mb4_general_ci`, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = MyISAM COMMENT = \'\' ');
        $this->addSql('CREATE TABLE playerstattoos (id INT AUTO_INCREMENT NOT NULL, identifier VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_general_ci`, tattoos VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_general_ci`, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE properties (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) CHARACTER SET latin1 DEFAULT NULL COLLATE `latin1_swedish_ci`, label VARCHAR(255) CHARACTER SET latin1 DEFAULT NULL COLLATE `latin1_swedish_ci`, entering VARCHAR(255) CHARACTER SET latin1 DEFAULT NULL COLLATE `latin1_swedish_ci`, `exit` VARCHAR(255) CHARACTER SET latin1 DEFAULT NULL COLLATE `latin1_swedish_ci`, inside VARCHAR(255) CHARACTER SET latin1 DEFAULT NULL COLLATE `latin1_swedish_ci`, outside VARCHAR(255) CHARACTER SET latin1 DEFAULT NULL COLLATE `latin1_swedish_ci`, ipls VARCHAR(255) CHARACTER SET latin1 DEFAULT \'[]\' COLLATE `latin1_swedish_ci`, gateway VARCHAR(255) CHARACTER SET latin1 DEFAULT NULL COLLATE `latin1_swedish_ci`, is_single INT DEFAULT NULL, is_room INT DEFAULT NULL, is_gateway INT DEFAULT NULL, room_menu VARCHAR(255) CHARACTER SET latin1 DEFAULT NULL COLLATE `latin1_swedish_ci`, price INT NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE rented_aircrafts (plate VARCHAR(12) CHARACTER SET latin1 NOT NULL COLLATE `latin1_swedish_ci`, vehicle VARCHAR(60) CHARACTER SET latin1 NOT NULL COLLATE `latin1_swedish_ci`, player_name VARCHAR(255) CHARACTER SET latin1 NOT NULL COLLATE `latin1_swedish_ci`, base_price INT NOT NULL, rent_price INT NOT NULL, owner VARCHAR(30) CHARACTER SET latin1 NOT NULL COLLATE `latin1_swedish_ci`, PRIMARY KEY(plate)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = MyISAM COMMENT = \'\' ');
        $this->addSql('CREATE TABLE rented_boats (plate VARCHAR(12) CHARACTER SET latin1 NOT NULL COLLATE `latin1_swedish_ci`, vehicle VARCHAR(60) CHARACTER SET latin1 NOT NULL COLLATE `latin1_swedish_ci`, player_name VARCHAR(255) CHARACTER SET latin1 NOT NULL COLLATE `latin1_swedish_ci`, base_price INT NOT NULL, rent_price INT NOT NULL, owner VARCHAR(30) CHARACTER SET latin1 NOT NULL COLLATE `latin1_swedish_ci`, PRIMARY KEY(plate)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = MyISAM COMMENT = \'\' ');
        $this->addSql('CREATE TABLE rented_vehicles (plate VARCHAR(12) CHARACTER SET latin1 NOT NULL COLLATE `latin1_swedish_ci`, vehicle VARCHAR(60) CHARACTER SET latin1 NOT NULL COLLATE `latin1_swedish_ci`, player_name VARCHAR(255) CHARACTER SET latin1 NOT NULL COLLATE `latin1_swedish_ci`, base_price INT NOT NULL, rent_price INT NOT NULL, owner VARCHAR(22) CHARACTER SET latin1 NOT NULL COLLATE `latin1_swedish_ci`, PRIMARY KEY(plate)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE shops (id INT AUTO_INCREMENT NOT NULL, store VARCHAR(100) CHARACTER SET latin1 NOT NULL COLLATE `latin1_swedish_ci`, item VARCHAR(100) CHARACTER SET latin1 NOT NULL COLLATE `latin1_swedish_ci`, price INT NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE shops2 (id INT AUTO_INCREMENT NOT NULL, store VARCHAR(100) CHARACTER SET latin1 NOT NULL COLLATE `latin1_swedish_ci`, item VARCHAR(100) CHARACTER SET latin1 NOT NULL COLLATE `latin1_swedish_ci`, price INT NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE society_moneywash (id INT AUTO_INCREMENT NOT NULL, identifier VARCHAR(60) CHARACTER SET latin1 NOT NULL COLLATE `latin1_swedish_ci`, society VARCHAR(60) CHARACTER SET latin1 NOT NULL COLLATE `latin1_swedish_ci`, amount INT NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE truck_inventory (id INT AUTO_INCREMENT NOT NULL, item VARCHAR(100) CHARACTER SET latin1 NOT NULL COLLATE `latin1_swedish_ci`, count INT NOT NULL, plate VARCHAR(8) CHARACTER SET latin1 NOT NULL COLLATE `latin1_swedish_ci`, name VARCHAR(255) CHARACTER SET latin1 NOT NULL COLLATE `latin1_swedish_ci`, itemt VARCHAR(50) CHARACTER SET latin1 DEFAULT NULL COLLATE `latin1_swedish_ci`, owned VARCHAR(255) CHARACTER SET latin1 NOT NULL COLLATE `latin1_swedish_ci`, UNIQUE INDEX item (item, plate), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE twitter_accounts (id INT AUTO_INCREMENT NOT NULL, username VARCHAR(50) CHARACTER SET utf8 DEFAULT \'0\' NOT NULL COLLATE `utf8_general_ci`, password VARCHAR(64) CHARACTER SET utf8mb4 DEFAULT \'0\' NOT NULL COLLATE `utf8mb4_bin`, avatar_url VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_bin`, UNIQUE INDEX username (username), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE twitter_likes (id INT AUTO_INCREMENT NOT NULL, authorId INT DEFAULT NULL, tweetId INT DEFAULT NULL, INDEX FK_twitter_likes_twitter_tweets (tweetId), INDEX FK_twitter_likes_twitter_accounts (authorId), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE twitter_tweets (id INT AUTO_INCREMENT NOT NULL, authorId INT NOT NULL, realUser VARCHAR(50) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, message VARCHAR(256) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, time DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL, likes INT DEFAULT 0 NOT NULL, INDEX FK_twitter_tweets_twitter_accounts (authorId), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE user_accessories (id INT AUTO_INCREMENT NOT NULL, identifier VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_bin`, mask VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_bin`, label VARCHAR(50) CHARACTER SET utf8mb4 DEFAULT \'Masque\' COLLATE `utf8mb4_bin`, type VARCHAR(50) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_bin`, `index` INT DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = MyISAM COMMENT = \'\' ');
        $this->addSql('CREATE TABLE user_accounts (id INT AUTO_INCREMENT NOT NULL, identifier VARCHAR(22) CHARACTER SET latin1 NOT NULL COLLATE `latin1_swedish_ci`, name VARCHAR(50) CHARACTER SET latin1 NOT NULL COLLATE `latin1_swedish_ci`, money DOUBLE PRECISION DEFAULT \'0\' NOT NULL, INDEX identifier (identifier), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE user_contacts (id INT AUTO_INCREMENT NOT NULL, identifier VARCHAR(22) CHARACTER SET latin1 NOT NULL COLLATE `latin1_swedish_ci`, name VARCHAR(100) CHARACTER SET latin1 NOT NULL COLLATE `latin1_swedish_ci`, number INT NOT NULL, INDEX index_user_contacts_identifier_name_number (identifier, name, number), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE user_inventory (id INT AUTO_INCREMENT NOT NULL, identifier VARCHAR(22) CHARACTER SET latin1 NOT NULL COLLATE `latin1_swedish_ci`, item VARCHAR(50) CHARACTER SET latin1 NOT NULL COLLATE `latin1_swedish_ci`, count INT NOT NULL, INDEX identifier (identifier), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE user_licenses (id INT AUTO_INCREMENT NOT NULL, type VARCHAR(60) CHARACTER SET latin1 NOT NULL COLLATE `latin1_swedish_ci`, owner VARCHAR(60) CHARACTER SET latin1 NOT NULL COLLATE `latin1_swedish_ci`, INDEX owner (owner), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE user_parkings (id INT AUTO_INCREMENT NOT NULL, identifier VARCHAR(60) CHARACTER SET latin1 DEFAULT NULL COLLATE `latin1_swedish_ci`, garage VARCHAR(60) CHARACTER SET latin1 DEFAULT NULL COLLATE `latin1_swedish_ci`, zone INT NOT NULL, vehicle LONGTEXT CHARACTER SET latin1 DEFAULT NULL COLLATE `latin1_swedish_ci`, INDEX identifier (identifier), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE user_tenue (id INT AUTO_INCREMENT NOT NULL, identifier VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_bin`, tenue LONGTEXT CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_bin`, label VARCHAR(20) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_bin`, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = MyISAM COMMENT = \'\' ');
        $this->addSql('CREATE TABLE vehicle_categories (name VARCHAR(60) CHARACTER SET latin1 NOT NULL COLLATE `latin1_swedish_ci`, label VARCHAR(60) CHARACTER SET latin1 NOT NULL COLLATE `latin1_swedish_ci`, PRIMARY KEY(name)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE vehicle_sold (plate VARCHAR(50) CHARACTER SET latin1 NOT NULL COLLATE `latin1_swedish_ci`, client VARCHAR(50) CHARACTER SET latin1 NOT NULL COLLATE `latin1_swedish_ci`, model VARCHAR(50) CHARACTER SET latin1 NOT NULL COLLATE `latin1_swedish_ci`, soldby VARCHAR(50) CHARACTER SET latin1 NOT NULL COLLATE `latin1_swedish_ci`, date VARCHAR(50) CHARACTER SET latin1 NOT NULL COLLATE `latin1_swedish_ci`, PRIMARY KEY(plate)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE vehicles (model VARCHAR(60) CHARACTER SET latin1 NOT NULL COLLATE `latin1_swedish_ci`, name VARCHAR(60) CHARACTER SET latin1 NOT NULL COLLATE `latin1_swedish_ci`, price INT NOT NULL, category VARCHAR(60) CHARACTER SET latin1 DEFAULT NULL COLLATE `latin1_swedish_ci`, PRIMARY KEY(model)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE weashops (id INT AUTO_INCREMENT NOT NULL, zone VARCHAR(255) CHARACTER SET latin1 NOT NULL COLLATE `latin1_swedish_ci`, item VARCHAR(255) CHARACTER SET latin1 NOT NULL COLLATE `latin1_swedish_ci`, price INT NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE whitelist (identifier VARCHAR(40) CHARACTER SET utf8 NOT NULL COLLATE `utf8_bin`, PRIMARY KEY(identifier)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('ALTER TABLE twitter_likes ADD CONSTRAINT FK_twitter_likes_twitter_accounts FOREIGN KEY (authorId) REFERENCES twitter_accounts (id)');
        $this->addSql('ALTER TABLE twitter_likes ADD CONSTRAINT FK_twitter_likes_twitter_tweets FOREIGN KEY (tweetId) REFERENCES twitter_tweets (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE twitter_tweets ADD CONSTRAINT FK_twitter_tweets_twitter_accounts FOREIGN KEY (authorId) REFERENCES twitter_accounts (id)');
        $this->addSql('ALTER TABLE users MODIFY id INT NOT NULL');
        $this->addSql('ALTER TABLE users DROP FOREIGN KEY FK_1483A5E99D86650F');
        $this->addSql('DROP INDEX UNIQ_1483A5E99D86650F ON users');
        $this->addSql('ALTER TABLE users DROP PRIMARY KEY');
        $this->addSql('ALTER TABLE users DROP id, DROP user_id_id, CHANGE name name VARCHAR(50) CHARACTER SET utf8mb4 DEFAULT \'\' NOT NULL COLLATE `utf8mb4_bin`, CHANGE job job VARCHAR(50) CHARACTER SET utf8mb4 DEFAULT \'unemployed\' COLLATE `utf8mb4_bin`, CHANGE job_grade job_grade INT DEFAULT 0, CHANGE job2 job2 VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'unemployed2\' COLLATE `utf8mb4_bin`, CHANGE job2_grade job2_grade INT DEFAULT 0, CHANGE is_dead is_dead TINYINT(1) DEFAULT \'0\', CHANGE firstname firstname VARCHAR(50) CHARACTER SET utf8mb4 DEFAULT \'\' COLLATE `utf8mb4_bin`, CHANGE lastname lastname VARCHAR(50) CHARACTER SET utf8mb4 DEFAULT \'\' COLLATE `utf8mb4_bin`, CHANGE dateofbirth dateofbirth VARCHAR(25) CHARACTER SET utf8mb4 DEFAULT \'\' COLLATE `utf8mb4_bin`, CHANGE sex sex VARCHAR(10) CHARACTER SET utf8mb4 DEFAULT \'\' COLLATE `utf8mb4_bin`, CHANGE height height VARCHAR(5) CHARACTER SET utf8mb4 DEFAULT \'\' COLLATE `utf8mb4_bin`, CHANGE status status LONGTEXT CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_bin`, CHANGE jail jail INT DEFAULT 0 NOT NULL, CHANGE phone_number phone_number VARCHAR(10) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_bin`');
        $this->addSql('CREATE UNIQUE INDEX identifier ON users (identifier)');
        $this->addSql('CREATE INDEX name ON users (name)');
    }
}
